# Generated by Django 3.1 on 2021-09-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_auto_20210901_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('UPI', 'UPI')], default='Cash On Delivery', max_length=20),
        ),
    ]
