# Generated by Django 3.1 on 2021-09-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0010_auto_20210901_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('UPI', 'UPI')], default='UPI', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PAYMENT INITIATED', 'PAYMENT INITIATED'), ('PAYMENT DONE', 'PAYMENT DONE'), ('PAYMENT PENDING', 'PAYMENT PENDING')], default='Payment Initiated', max_length=50),
        ),
    ]
